### ISSUE TITLE
Improve consistency of how Tcp Connection resources are cleaned up

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#45]

**Comment by JerryShea** [comment]
@peter-lawrey there are a few corner cases here and calling action() to close just feels a bit odd. How about we add a new method to tell the EventHandler that execution has completed and action() won't be called again e.g. terminated() or onTerminated()?
I will do on Monday if I don't hear otherwise.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Network-2.17.16](https://github.com/OpenHFT/Chronicle-Network/releases/chronicle-network-2.17.16), [BOM-2.17.446](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.446)
